[Base]
PortBaseSel=0
PortMappingSel=0
ForceRomMode=1
SnSeparateIni=1
RemoteSnPath=D:\Public_Code\GitRepos\SparkUfsPdt\RemoteSN.ini
ReportPath=D:\Public_Code\GitRepos\SparkUfsPdt\SMISUM
LastSettingPath=D:\Public_Code\GitRepos\SparkUfsPdt\SparkUfsPdt\Setting\FT3.ini
COM=COM1
BaudRate=9600
ByteSize=8
;1:1, 2:2，3:1.5, 
StopBits=1
;0:None, 1:Odd, 2:Even, 3:Mark, 4:Space  
Parity=0
